name: build-bundles
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  wasm:
    runs-on: ubuntu-latest
    env:
      AR: llvm-ar-15
      CC: clang-15
      CXX: clang++-15
      LLVM_CONFIG: llvm-config-15
      NM: llvm-nm-15
    steps:
      - run: sudo apt-get install -y ninja-build
      - run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: ./wasi.sh
      - uses: actions/upload-artifact@v3
        with:
          name: install-prefix
          path: prefix/
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: cmake -G Ninja -S llvm-project/runtimes -B build/runtimes -DLLVM_ENABLE_RUNTIMES="libcxx" -DLIBCXX_CXX_ABI="vcruntime" -DCMAKE_C_COMPILER="clang-cl" -DCMAKE_CXX_COMPILER="clang-cl"
      - run: ninja -C build/runtimes cxx
      - run: ninja -C build/runtimes install-cxx
