name: wasm-bundle
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AR: llvm-ar-15
      CC: clang-15
      CXX: clang++-15
      LLVM_CONFIG: llvm-config-15
      NM: llvm-nm-15
    steps:
      - run: sudo apt-get install -y ninja-build
      - run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: ./wasi.sh
      - uses: actions/upload-artifact@v3
        with:
          name: install-prefix
          path: prefix/
