name: wasm-bundle
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
    steps:
      - run: sudo apt-get install -y llvm
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: ./wasi.sh
      - uses: actions/upload-artifact@v3
        with:
          name: install-prefix
          path: prefix/
